package com.gawpdevelopers.gawp.domain;

public enum DepartmentType {
    COMPUTERENGINEERING,
    MECHANICALENGINEERING,
    ELECTRONICANDCOMMUNUCATIONENGINNERING,
    FOODENGINEERING,
    CIVILENGINEERING,
    PHYSICS,
    CHEMISTRY,
    MATHEMATICS
}
